In [1]:
from aeon.datasets import load_classification
from tscglue.models import LokyStackerV8Base

In [2]:

# DodgerLoopDay: univariate dataset with missing values
X_train, y_train = load_classification("DodgerLoopDay", split="train")
X_test, y_test   = load_classification("DodgerLoopDay", split="test")

import numpy as np
print(f"train: {X_train.shape}, test: {X_test.shape}")
print(f"Has NaN in train: {np.isnan(X_train).any()}, in test: {np.isnan(X_test).any()}")

model = LokyStackerV8Base(random_state=492, n_repetitions=1, n_jobs=16, keep_features=True, verbose=2)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score
print(f"accuracy: {accuracy_score(y_test, y_pred):.4f}")


train: (67, 1, 288), test: (77, 1, 288)
Has NaN in train: False, in test: False
[0.00s] Starting executor with 16 workers, run_dir=./tscglue_runs/a2b38aa89a244dae
[0.00s] Saved X and y to disk in 0.00s
[0.14s] Computed QUANT features (67, 2769) (1.42 MB) in 0.1380s
[0.18s] Starting repetition 0
[1.38s] Computed MultiRocket features (67, 49728) (25.42 MB) in 1.2046s
[1.53s] Computed Hydra features (67, 6144) (3.14 MB) in 0.1462s
[2.54s] Computed RDST features (67, 30000) (15.34 MB) in 1.0162s
[2.55s] Starting training with 16 workers for 40 models


/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(


[7.74s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.3241s for f-0/r-0 (3.01 MB)
[7.74s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.3278s for f-1/r-0 (3.01 MB)
[7.76s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.3308s for f-2/r-0 (3.01 MB)
[7.76s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.3271s for f-3/r-0 (3.01 MB)
[7.79s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.3283s for f-4/r-0 (3.01 MB)
[7.81s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.3294s for f-5/r-0 (3.01 MB)
[8.00s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.2558s for f-6/r-0 (3.01 MB)
[8.02s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.2725s for f-7/r-0 (3.01 MB)
[8.03s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.2646s for f-9/r-0 (3.01 MB)
[8.03s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.2686s for f-8/r-0 (3.01 MB)
[8.03s] Completed training for model multirockethydra-bestk-p-ridgecv_r0
[8.04s] OOF acc for model multirockethydra-bestk-p-ridgecv_r0: 0.611940298507

In [13]:
X_train, y_train = load_classification("MelbournePedestrian", split="train", load_no_missing=False)
X_train

[array([[  97.,   42.,   20.,   10.,   14.,   33.,  113.,  422.,  875.,
         1003., 1351., 1613., 2937., 2954., 2167., 2330., 2191., 2621.,
         2400., 1892., 1253.,  844.,  438.,  204.]]),
 array([[ 107.,   50.,   41.,   17.,   48.,   35.,  102.,  326.,  856.,
          956., 1397., 2079., 3570., 3857., 2999., 3032., 2794., 3061.,
         2323., 1463.,  773.,  646.,  305.,  158.]]),
 array([[ 416.,  193.,   75.,   82.,   49.,   38.,  150.,  232.,  461.,
          907., 1548., 2294., 3253., 3690., 3809., 3675., 3494., 3366.,
         3265., 2272., 2178., 2175., 1750.,  871.]]),
 array([[ 309.,  229.,  142.,  143.,   74.,   70.,   62.,   82.,  198.,
          761., 1517., 2398., 3225., 3541., 3614., 3501., 3239., 2839.,
         2159., 1365.,  762.,  497., 1146.,  546.]]),
 array([[ 277.,  169.,   99.,   91.,   27.,   39.,   53.,   83.,  169.,
          665., 1247., 2124., 2249., 2615., 2873., 3081., 3065., 2554.,
         1868., 1009.,  538.,  394.,  234.,  137.]]),
 array([[ 

In [ ]:
MelbournePedestrian